streams:
  cam1: rtsp://root:demo1234@192.168.1.155/live1s1.sdp

modules: [streams, api, rtsp, webrtc]

http:   { bind: ":1984" }
webrtc: { bind: ":8555",
          ice_servers: [{ urls: ["stun:stun.l.google.com:19302"] }] }
